# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

a=1
b=0
c=1
l=[]
count=0
sum=0


while count < a:
        if b>4000000:
                break
        else:
                l.append(b) 
                d= b+c
                b=c
                c=d
                count += 1  
                a+=1

for i in l:
        if i%2==0:
                sum=sum+i
print(sum)
